name: 'Datadog Synthetics CI'
description: 'Trigger your Datadog Synthetics test using the datadog-ci tool'
author: 'DataDog'
inputs:
  api_key: 
    required: true
    description: 'Datadog API key'
  app_key: 
    required: true
    description: 'Datadog Application key'
  datadog_site: 
    required: false
    description: 'Datadog site'
  public_ids: 
    required: true
    description: 'Public IDs of Synthetics test to run'
  
runs:
  using: docker
  image: Dockerfile
