name: 'Datadog Synthetics CI'
description: 'Run Datadog Synthetics CI tests as part of your Github Actions workflow'
author: 'Datadog'
inputs:
  api-key:
    required: true
    description: 'Your Datadog API key.'
  app-key:
    required: true
    description: 'Your Datadog application key.'
  batch-timeout:
    required: false
    description: 'The duration in milliseconds after which the CI batch fails as timed out.'
  config-path:
    required: false
    description: 'The path to the global configuration file that configures datadog-ci.'
  datadog-site:
    required: false
    description: 'Your Datadog site.'
  fail-on-critical-errors:
    required: false
    description: 'Fail the CI job if no tests were triggered, or results could not be fetched from Datadog.'
  fail-on-missing-tests:
    required: false
    description: 'Fail the CI job if at least one specified test with a public ID (using `public_ids` or listed in a test file) is missing in a run (for example, if it has been deleted programmatically or on the Datadog site).'
  fail-on-timeout:
    required: false
    description: 'Fail the CI job if at least one test exceeds the default test timeout.'
  files:
    required: false
    description: 'Glob pattern to detect Synthetic tests config.'
  junit-report:
    required: false
    description: 'The filename for a JUnit report if you want to generate one.'
  public-ids:
    required: false
    description: 'Public IDs of Synthetic tests to run, separated by new lines or commas. If no value is provided, tests are discovered in `*.synthetics.json` files.'
  subdomain:
    required: false
    description: 'Name of your Datadog custom subdomain.'
  test-search-query:
    required: false
    description: 'Search query to trigger tests.'
  tunnel:
    required: false
    description: 'Enable tunnel to interact with Datadog API.'
    default: 'false'
  variables:
    required: false
    description: 'Key-value pairs for injecting variables into tests, separated by newlines or commas. For example: `START_URL=https://example.org,MY_VARIABLE=My title`.'

outputs:
  batch-url:
    description: 'The URL of the batch.'
  critical-errors-count:
    description: 'The number of critical errors.'
  failed-count:
    description: 'The number of failed results.'
  failed-non-blocking-count:
    description: 'The number of failed non-blocking results.'
  passed-count:
    description: 'The number of passed results.'
  previously-passed-count:
    description: 'The number of previously passed results.'
  tests-not-found-count:
    description: 'The number of not found tests.'
  tests-skipped-count:
    description: 'The number of skipped tests.'
  timed-out-count:
    description: 'The number of timed out results.'
  raw-results:
    description: 'The list of results, as a raw JSON string.'

runs:
  using: 'node20'
  main: 'dist/index.js'
