name: 'Datadog Synthetics CI'
description: 'Run Datadog Synthetics CI tests as part of your Github Actions workflow'
author: 'Datadog'
inputs:
  api_key:
    required: true
    description: 'Datadog API key.'
  app_key:
    required: true
    description: 'Datadog Application key.'
  batch_timeout:
    required: false
    description: 'The duration (in milliseconds) after which the batch fails as timed out.'
  config_path:
    required: false
    description: 'Path to global configuration JSON.'
  datadog_site:
    required: false
    description: 'Datadog site.'
  fail_on_critical_errors:
    required: false
    description: 'Fail the CI job if no tests were triggered, or results could not be fetched from Datadog.'
  fail_on_missing_tests:
    required: false
    description: 'Fail the CI job if at least one specified test with a public ID (using `public_ids` or listed in a test file) is missing in a run (for example, if it has been deleted programmatically or on the Datadog site).'
  fail_on_timeout:
    required: false
    description: 'Fail the CI job if at least one test exceeds the default test timeout.'
  files:
    required: false
    description: 'Glob pattern to detect Synthetic tests config.'
  junit_report:
    required: false
    description: 'The filename for a JUnit report if you want to generate one.'
  public_ids:
    required: false
    description: 'Public IDs of Synthetic tests to run, separated by new lines or commas. If no value is provided, tests are discovered in `*.synthetics.json` files.'
  subdomain:
    required: false
    description: 'Name of your Datadog custom subdomain.'
  test_search_query:
    required: false
    description: 'Search query to trigger tests.'
  tunnel:
    required: false
    description: 'Enable tunnel to interact with Datadog API.'
    default: false
  variables:
    required: false
    description: 'Key-value pairs for injecting variables into tests, separated by newlines or commas. For example: `START_URL=https://example.org,MY_VARIABLE=My title`.'

runs:
  using: 'node20'
  main: 'dist/index.js'
