issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/synthetics-ci-github-action:ref:refs/heads/main
claim_pattern:
  event_name: pull_request
  ref: refs/heads/main
  job_workflow_ref: DataDog/synthetics-ci-github-action/\.github/workflows/release-version-on-merge\.yml@.*

permissions:
  contents: write
