# This workflow will do a clean install of node dependencies, build the source code and run tests

name: Run unit tests

on: push

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn lint
      - run: yarn test
