# This workflow will do a clean install of node dependencies, build the source code and run tests

name: Run unit tests

on: push

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn lint
      - run: yarn test
