# This workflow will do a clean install of node dependencies, build the source code and run tests

name: Run unit tests

on: push

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - run: yarn package # Ensure `ncc` works
